In [14]:
#Create a null vector of size 10 but the fifth values is 1

import numpy as np
arr=np.zeros(shape=(10),dtype=int)


arr[4]=1
print(arr)
arr.size

[0 0 0 0 1 0 0 0 0 0]


10

In [15]:
#create vector with value ranging 10 to 49
import numpy as np
arr1= np.random.randn(10,49)

In [16]:
arr1

array([[-1.72557016e+00,  4.31750328e-01,  4.33953389e-01,
         2.91695277e-01, -8.37621909e-01,  1.32367106e-01,
         1.00268135e+00,  1.32092170e+00, -9.12041550e-01,
        -1.56032484e+00, -5.68194566e-01,  1.89516073e+00,
         7.62474105e-01, -5.57144793e-01, -9.95032423e-01,
         7.04787860e-01, -1.22008704e+00,  6.60569353e-01,
        -1.50042922e-01,  6.90305674e-01,  2.72448983e-01,
        -1.37110565e+00, -7.02751561e-01,  1.80877536e+00,
         1.02333595e-01,  6.41780962e-01,  6.80217148e-02,
        -6.92718327e-01,  5.44847281e-01,  2.65110665e-01,
         9.12505296e-01,  8.38941875e-01,  6.14265944e-02,
         6.89716327e-01, -1.09831793e+00,  2.22098856e-01,
         1.55549483e+00,  1.50832479e+00,  1.48716069e-01,
        -4.66189616e-01,  6.34565486e-01,  4.28326296e-01,
         3.40281544e-01, -1.14697756e+00, -4.04530127e-01,
         4.65275921e-01,  3.80797132e-01, -2.16765108e-01,
        -1.49403980e+00],
       [ 5.08258311e-03, -1.05

In [18]:
#create a 3X3 matrix with values ranging from 0 to 8

import numpy as np
arr2=np.random.randint(0,8,(3,3))
print(arr2)

[[3 5 7]
 [1 7 5]
 [0 7 2]]


In [36]:
#Find indices of non-zero elements from [1,2,0,0,4,0]


import numpy as np

arr3=np.array([1,2,0,0,4,0])
pos_arr=arr3[arr3>0]
print(pos_arr)



[1 2 4]


In [41]:
#create 10X10 matrix with some random values and find the minimuum values and maximum values

import numpy as np
arr4=np.random.randint(10,50,(10,10))
print(arr4)
arr4.min(), arr4.max()



[[21 43 27 20 16 24 40 37 20 41]
 [11 11 40 14 46 14 34 28 15 26]
 [16 16 35 14 40 25 40 49 32 16]
 [42 17 45 17 32 38 14 27 18 10]
 [10 19 24 42 11 22 40 31 35 12]
 [45 32 23 23 25 45 29 38 42 34]
 [36 24 46 35 44 14 24 47 49 25]
 [47 49 28 13 42 42 49 39 41 20]
 [33 16 19 35 45 49 46 20 23 11]
 [42 30 38 34 31 28 13 33 43 32]]


(10, 49)

In [46]:
#create random vector of size 30 and find mean value
import numpy as np
arr5=np.random.randint(10,50,(6,5))
print(arr5)
print(arr5.size)
print(arr5.mean())

[[10 37 38 44 29]
 [35 39 23 21 37]
 [47 32 48 24 46]
 [45 11 47 42 37]
 [28 13 25 27 13]
 [45 13 10 42 19]]
30
30.9
